version: 2.1

jobs:
  work:
    working_directory: ~/circlecitest
    parameters:
      env:
        type: string
        description: test
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Test
          command: |
            ls -a
            git init
            touch test
            git add .
            git commit -m "<<parameters.env>>"
            export branch="BRELSA"
            echo $branch
    

workflows:
  say-hello-workflow:
    jobs:
      - work:
          env: codepush upd [skip ic]
          filters:
            branches:
              only:
                circleci-project-setup
