version: 2.1

jobs:
  work:
    working_directory: ~/circlecitest
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Test
          command: |
            echo "start"
            export branch=$(git name-rev --name-only HEAD)
            echo $branch
    

workflows:
  say-hello-workflow:
    jobs:
      - work:
          filters:
            branches:
              only:
                circleci-project-setup
