version: 2.1

jobs:
  say-hello:
    work_directory: ~/circlecitest
    docker:
      - image: stedolan/jq
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: |
            jq -e '.version + 1' 'version.json' > 'version.json.tmp'
            cp 'version.json.tmp' 'version.json'
      - run:
          name: "Check"
          command: cat version.json
          

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
