version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: dir
          command: pwd
      - run:
          name: jq install
          command: sudo apt-get install jq
      - run:
          name: Say hello
          command: |
            jq -e ".version + 1" "version.json" > "version.json.tmp"
            cp "version.json.tmp" "version.json"
      - run:
          name: "Check"
          command: cat version.json
      - persist_to_workspace:
          name: next dir
          root: .
          paths:
            - .
  say-hey:
    docker:
      - image: cimg/base:stable
    steps: 
      - attach_workspace:
          at: .
      - run:
          name: Check
          command: cat version.json 

workflows:
  say-hello-workflow:
    jobs:
      - say-hello:
          filters:
            branches:
              only:
                circleci-project-setup

      - say-hey:
          requires:
            - say-hello
