version: 2.1

jobs:
  work:
    working_directory: ~/circlecitest
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Test
          command: |
            ls -a
            echo "start"
            export branch="BRELSA"
            echo $branch
    

workflows:
  say-hello-workflow:
    jobs:
      - work:
          filters:
            branches:
              only:
                circleci-project-setup
